name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3) Compile the Java file
      - name: Compile HelloWorld
        run: javac HelloWorld.java

      # 4) Run it
      - name: Run HelloWorld
        run: java HelloWorld
