name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 1) Download JUnit Console Standalone
      - name: Download JUnit console jar
        run: |
          curl -L -o junit-platform-console-standalone.jar \
            https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.3/junit-platform-console-standalone-1.9.3.jar

      # 2) Compile both source and test (needs the jar)
      - name: Compile Java & Test
        run: |
          javac -cp junit-platform-console-standalone.jar HelloWorld.java HelloWorldTest.java

      # 3) Run the main
      - name: Run HelloWorld
        run: java HelloWorld

      # 4) Run only your test class explicitly
      - name: Run HelloWorldTest
        run: |
          java -jar junit-platform-console-standalone.jar \
            --class-path . \
            --select-class HelloWorldTest
